version: "3"
services:
  hub:
    image: selenium/hub:4.16
    ports:
      - 4444:4444
      # - 4442:4442
      # - 4443:4443

  chrome:
    image: selenium/node-chrome:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  vendor-portal:
    image: gk403/text
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=testng2.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
